import assert from 'node:assert/strict';
import test from 'node:test';
import { PGlite } from '@electric-sql/pglite';
import { applyRosterImport } from '../ops/releases/k56-class-access-20260924/roster_import.mjs';

const slugs = ['term-test-1-k56', 'term-test-2-k56', 'mini-test-k56'];
const oldRows = slugs.map((test_slug, index) => ({
  test_slug, class_id: '1252', contact_id: '101',
  student_ref: `00000000-0000-4000-8000-${String(index + 1).padStart(12, '0')}`,
  student_name: 'Học viên giả A'
}));
const newRows = slugs.map((test_slug, index) => ({
  test_slug, class_id: '2322', contact_id: '202',
  student_ref: `00000000-0000-4000-9000-${String(index + 1).padStart(12, '0')}`,
  student_name: 'Học viên giả B'
}));

const payload = () => ({
  syncRunId: '102',
  summary: { syncRunId: '102', classMappingsToAdd: 1,
    rosterRowsToAdd: 3, testCount: 3 },
  expectedMappings: [{ class_id: '1252', class_code: 'IC2264' }],
  expectedRoster: oldRows.map(row => ({ ...row })),
  newMappings: [{ class_id: '2322', class_code: 'IC2322' }],
  newRoster: newRows.map(row => ({ ...row }))
});

async function setup({ gate = true } = {}) {
  // Dữ liệu vào: schema và hai học viên giả; không có dữ liệu production.
  // Việc chính: dựng kho K56 tối thiểu với ba đề và cổng quyền tùy ca test.
  // Kết quả: PostgreSQL trong RAM; lỗi setup làm test thất bại.
  const db = new PGlite();
  await db.exec(`
    CREATE SCHEMA mapping;
    CREATE SCHEMA assessment;
    CREATE TABLE mapping.classroom_course_mapping (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      erp_course_class_id BIGINT UNIQUE NOT NULL,
      erp_class_name_snapshot TEXT NOT NULL,
      classroom_course_id TEXT,
      status TEXT NOT NULL DEFAULT 'pending_review'
    );
    CREATE TABLE assessment.term_test_roster (
      test_slug TEXT NOT NULL,
      erp_course_class_id BIGINT NOT NULL,
      erp_student_contact_id BIGINT NOT NULL,
      student_ref UUID NOT NULL,
      student_name_snapshot TEXT NOT NULL CHECK (student_name_snapshot <> 'FAIL'),
      PRIMARY KEY (test_slug, erp_course_class_id, erp_student_contact_id),
      UNIQUE (test_slug, student_ref)
    );
    INSERT INTO mapping.classroom_course_mapping
      (erp_course_class_id, erp_class_name_snapshot)
      VALUES (1252, 'IC2264');
  `);
  if (gate) {
    await db.exec(`
      CREATE TABLE assessment.term_test_class_access (
        test_slug TEXT NOT NULL,
        erp_course_class_id BIGINT NOT NULL,
        enabled BOOLEAN NOT NULL DEFAULT false,
        PRIMARY KEY (test_slug, erp_course_class_id)
      );
    `);
    for (const slug of slugs) {
      await db.query(`INSERT INTO assessment.term_test_class_access VALUES ($1, 1252, true)`,
        [slug]);
    }
  }
  for (const row of oldRows) {
    await db.query(`INSERT INTO assessment.term_test_roster VALUES ($1, $2, $3, $4, $5)`,
      [row.test_slug, row.class_id, row.contact_id,
        row.student_ref, row.student_name]);
  }
  return db;
}

function testDatabase(db) {
  return {
    query: (sql, params) => sql === 'SELECT current_database() AS name'
      ? Promise.resolve({ rows: [{ name: 'pglite_test' }] })
      : db.query(sql, params)
  };
}

function sharedTestDatabase(db) {
  return {
    query: (sql, params) => sql === 'SELECT current_database() AS name'
      ? Promise.resolve({ rows: [{ name: 'pglite_shared_test' }] })
      : db.query(sql, params)
  };
}

async function snapshot(db) {
  const mappings = (await db.query(`SELECT erp_course_class_id::text AS class_id,
    erp_class_name_snapshot AS class_code, classroom_course_id, status
    FROM mapping.classroom_course_mapping ORDER BY erp_course_class_id`)).rows;
  const roster = (await db.query(`SELECT test_slug,
    erp_course_class_id::text AS class_id,
    erp_student_contact_id::text AS contact_id,
    student_ref::text AS student_ref, student_name_snapshot AS student_name
    FROM assessment.term_test_roster ORDER BY test_slug, erp_course_class_id`)).rows;
  return { mappings, roster };
}

test('nhập một chiều giữ ba UUID cũ và để Classroom chưa duyệt', async () => {
  const db = await setup();
  try {
    const result = await applyRosterImport(testDatabase(db), payload(), 'pglite_test');
    assert.equal(result.businessOutcome, 'import_readback_verified');
    assert.equal(result.classMappingsAdded, 1);
    assert.equal(result.rosterRowsAdded, 3);
    assert.equal(result.rosterRowsPreserved, 3);
    const readback = await snapshot(db);
    assert.equal(readback.mappings.length, 2);
    assert.equal(readback.roster.length, 6);
    assert.equal(readback.mappings[1].classroom_course_id, null);
    assert.equal(readback.mappings[1].status, 'pending_review');
    for (const row of oldRows) {
      assert.ok(readback.roster.some(existing =>
        existing.test_slug === row.test_slug && existing.student_ref === row.student_ref));
    }
    assert.equal((await db.query(`SELECT count(*)::int AS count
      FROM assessment.term_test_class_access`)).rows[0].count, 3);
  } finally { await db.close(); }
});

test('kho chung nhập roster IC2322/IC2326 không ghép Classroom hoặc chạm K67', async () => {
  const db = await setup();
  try {
    await db.exec(`
      ALTER SCHEMA assessment RENAME TO assessment_k56;
      CREATE SCHEMA assessment;
      CREATE TABLE assessment.term_test_roster (test_slug TEXT PRIMARY KEY);
      INSERT INTO assessment.term_test_roster VALUES ('term-test-1');
      INSERT INTO mapping.classroom_course_mapping
        (erp_course_class_id, erp_class_name_snapshot) VALUES
        (2322, 'IC2322'), (2326, 'IC2326');
    `);
    const candidates = ['2322', '2326'].flatMap((classId, classIndex) =>
      slugs.map((test_slug, slugIndex) => ({
        test_slug, class_id: classId, contact_id: String(202 + classIndex),
        student_ref: `00000000-0000-4000-${classIndex ? 'a000' : '9000'}-${String(slugIndex + 1).padStart(12, '0')}`,
        student_name: classIndex ? 'Học viên giả C' : 'Học viên giả B'
      })));
    const request = {
      syncRunId: '102',
      summary: { syncRunId: '102', classMappingsToAdd: 0,
        rosterRowsToAdd: 6, testCount: 3 },
      expectedMappings: [
        { class_id: '1252', class_code: 'IC2264' },
        { class_id: '2322', class_code: 'IC2322' },
        { class_id: '2326', class_code: 'IC2326' }
      ],
      expectedRoster: oldRows.map(row => ({ ...row })),
      newMappings: [], newRoster: candidates
    };
    const result = await applyRosterImport(sharedTestDatabase(db), request,
      'pglite_shared_test');
    assert.equal(result.classMappingsAdded, 0);
    assert.equal(result.rosterRowsAdded, 6);
    const imported = await db.query(`SELECT erp_course_class_id::int AS class_id,
      count(*)::int AS rows FROM assessment_k56.term_test_roster
      GROUP BY erp_course_class_id ORDER BY erp_course_class_id`);
    assert.deepEqual(imported.rows,
      [{ class_id: 1252, rows: 3 }, { class_id: 2322, rows: 3 },
        { class_id: 2326, rows: 3 }]);
    assert.deepEqual((await db.query('SELECT test_slug FROM assessment.term_test_roster')).rows,
      [{ test_slug: 'term-test-1' }]);
    const classroom = await db.query(`SELECT classroom_course_id
      FROM mapping.classroom_course_mapping WHERE erp_course_class_id IN (2322, 2326)`);
    assert.deepEqual(classroom.rows, [
      { classroom_course_id: null }, { classroom_course_id: null }
    ]);
  } finally { await db.close(); }
});

test('thiếu cổng quyền hoặc sai database thì không ghi', async () => {
  const noGate = await setup({ gate: false });
  try {
    await assert.rejects(applyRosterImport(testDatabase(noGate), payload(), 'pglite_test'),
      /CLASS_ACCESS_GATE_NOT_INSTALLED/);
    assert.equal((await snapshot(noGate)).mappings.length, 1);
  } finally { await noGate.close(); }
  const wrongDatabase = await setup();
  try {
    await assert.rejects(applyRosterImport(wrongDatabase, payload(), 'pglite_test'),
      /WRONG_TARGET_DATABASE/);
    assert.equal((await snapshot(wrongDatabase)).roster.length, 3);
  } finally { await wrongDatabase.close(); }
});

test('đích đổi sau preview thì dừng trước khi ghi', async () => {
  const db = await setup();
  try {
    await db.query(`UPDATE assessment.term_test_roster
      SET student_name_snapshot = 'Tên giả đã đổi' WHERE test_slug = $1`, [slugs[0]]);
    await assert.rejects(applyRosterImport(testDatabase(db), payload(), 'pglite_test'),
      /TARGET_CHANGED_SINCE_PREVIEW/);
    assert.equal((await snapshot(db)).mappings.length, 1);
  } finally { await db.close(); }
});

test('lỗi ở giữa lô rollback cả lớp và roster', async () => {
  const db = await setup();
  try {
    const bad = payload();
    bad.newRoster[1].student_name = 'FAIL';
    await assert.rejects(applyRosterImport(testDatabase(db), bad, 'pglite_test'),
      /IMPORT_TRANSACTION_FAILED/);
    assert.equal((await snapshot(db)).mappings.length, 1);
    assert.equal((await snapshot(db)).roster.length, 3);
  } finally { await db.close(); }
});

test('chạy lại cùng snapshot không tạo hàng hay UUID mới', async () => {
  const db = await setup();
  try {
    await applyRosterImport(testDatabase(db), payload(), 'pglite_test');
    const before = await snapshot(db);
    const rerun = { syncRunId: '102',
      summary: { syncRunId: '102', classMappingsToAdd: 0,
        rosterRowsToAdd: 0, testCount: 3 },
      expectedMappings: before.mappings.map(row => ({
      class_id: row.class_id, class_code: row.class_code
    })), expectedRoster: before.roster, newMappings: [], newRoster: [] };
    const result = await applyRosterImport(testDatabase(db), rerun, 'pglite_test');
    assert.equal(result.classMappingsAdded, 0);
    assert.equal(result.rosterRowsAdded, 0);
    assert.deepEqual(await snapshot(db), before);
  } finally { await db.close(); }
});

test('trùng khóa hoặc UUID bị chặn trước transaction', async () => {
  const db = await setup();
  try {
    const duplicate = payload();
    duplicate.newRoster.push({ ...duplicate.newRoster[0] });
    duplicate.summary.rosterRowsToAdd = 4;
    await assert.rejects(applyRosterImport(testDatabase(db), duplicate, 'pglite_test'),
      /DUPLICATE_NEW_ROSTER/);
    const duplicateRef = payload();
    duplicateRef.newRoster[0].student_ref = oldRows[0].student_ref;
    await assert.rejects(applyRosterImport(testDatabase(db), duplicateRef, 'pglite_test'),
      /DUPLICATE_NEW_STUDENT_REF/);
    assert.equal((await snapshot(db)).roster.length, 3);
  } finally { await db.close(); }
});

test('lớp ngoài phạm vi không đổi và học viên trùng tên vẫn tách theo ID', async () => {
  const db = await setup();
  try {
    await db.query(`INSERT INTO mapping.classroom_course_mapping
      (erp_course_class_id, erp_class_name_snapshot) VALUES (9999, 'IC9999')`);
    await db.query(`INSERT INTO assessment.term_test_roster VALUES ($1, 9999, 999,
      '00000000-0000-4000-8000-000000000099', 'Ngoài phạm vi')`, [slugs[0]]);
    const before = await snapshot(db);
    const input = payload();
    input.expectedMappings.push({ class_id: '9999', class_code: 'IC9999' });
    input.expectedRoster.push({ test_slug: slugs[0], class_id: '9999',
      contact_id: '999', student_ref: '00000000-0000-4000-8000-000000000099',
      student_name: 'Ngoài phạm vi' });
    input.newRoster.forEach(row => { row.student_name = 'Học viên giả A'; });
    await applyRosterImport(testDatabase(db), input, 'pglite_test');
    const after = await snapshot(db);
    assert.deepEqual(after.mappings.find(row => row.class_id === '9999'),
      before.mappings.find(row => row.class_id === '9999'));
    assert.deepEqual(after.roster.find(row => row.class_id === '9999'),
      before.roster.find(row => row.class_id === '9999'));
    assert.equal(after.roster.filter(row => row.student_name === 'Học viên giả A').length, 6);
  } finally { await db.close(); }
});

test('mã lớp trùng với ID khác bị từ chối trước khi ghi', async () => {
  const db = await setup();
  try {
    const input = payload();
    input.newMappings[0].class_code = 'IC2264';
    await assert.rejects(applyRosterImport(testDatabase(db), input, 'pglite_test'),
      /DUPLICATE_CLASS_CODE/);
    assert.equal((await snapshot(db)).mappings.length, 1);
  } finally { await db.close(); }
});

test('mã lượt nguồn hoặc số hàng không khớp thì không bắt đầu giao dịch', async () => {
  const db = await setup();
  try {
    const wrongRun = payload();
    wrongRun.syncRunId = '103';
    await assert.rejects(applyRosterImport(testDatabase(db), wrongRun, 'pglite_test'),
      /IMPORT_SOURCE_LINEAGE_INVALID/);
    const missingRow = payload();
    missingRow.newRoster.pop();
    await assert.rejects(applyRosterImport(testDatabase(db), missingRow, 'pglite_test'),
      /IMPORT_SOURCE_LINEAGE_INVALID/);
    assert.equal((await snapshot(db)).roster.length, 3);
  } finally { await db.close(); }
});
