// Lớp/học viên giả; Chrome dùng source Pages thật. Link/nhận xét ghi và đọc qua API + SQL thật.
// Những API bài làm cũ dùng fixture; số bài nộp/điểm danh phải giữ nguyên bằng 0.
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {createRequire} from 'node:module';
import express from 'express';
import {setupDatabase,poolFrom} from './journey-comment-fixture.js';
import {createLearningRouter} from '../src/learning-routes.js';
const pages=process.env.PAGES_SOURCE_ROOT;
if(!pages)throw Error('Cần PAGES_SOURCE_ROOT trỏ đúng worktree Pages để kiểm source đang sửa.');
const {chromium}=createRequire(process.env.PLAYWRIGHT_PACKAGE||'C:/Users/ADMIN/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')('playwright');
const ref='60000000-0000-4000-8000-000000000001',second='60000000-0000-4000-8000-000000000002';
const assignment='70000000-0000-4000-8000-000000000001';
const reviewer={email:'teacher@example.test',displayName:'Cô thử nghiệm',canAccessAllClasses:false};
test('GV → SQL → link riêng → HV: nháp, retry, xung đột, ẩn, giao diện và dữ liệu cũ',{timeout:120000},async()=>{
 const {database}=await setupDatabase();
 await database.exec(await readFile(new URL('../ops/learning-migrations/202610070001_student_journey_comments.sql',import.meta.url),'utf8'));
 await database.exec(`INSERT INTO learning.class_journey_plan (erp_course_class_id,total_sessions,test_session_numbers,revision,confirmed_by_email,confirmed_at) VALUES (2139,3,ARRAY[2],1,'teacher@example.test',now())`);
 const pool=poolFrom(database),app=express();app.use(express.json());
 app.get('/api/auth/session',(_req,res)=>res.json({ok:true,reviewer}));
 const roster=[{studentRef:ref,name:'Học viên trùng tên',completeness:'complete',submissionId:'fixture',attendanceStatus:'self_confirmed'},
   {studentRef:second,name:'Học viên trùng tên',completeness:'incomplete',attendanceStatus:'not_confirmed'}];
 const currentNotes=async()=>new Map((await pool.query('SELECT * FROM learning.student_session_comment WHERE session_number=2')).rows.map(row=>[row.student_ref,{studentRef:row.student_ref,sessionNumber:2,noteText:row.note_text,visibility:row.visibility,revision:row.revision,authorDisplayName:row.author_display_name,updatedAt:row.updated_at}]));
 app.get('/api/learning/teacher/options',(_req,res)=>res.json({ok:true,reviewer,classes:[{class_id:'2139',class_name:'IC2139'}],assignments:[{assignment_id:assignment,class_id:'2139',class_name:'IC2139',session_number:2,title:'Buổi thử',status:'published'}]}));
 app.get('/api/learning/teacher/question-library',(_req,res)=>res.json({ok:true,items:[]}));
 app.get('/api/learning/teacher/form-drafts',(_req,res)=>res.json({ok:true,drafts:[]}));
 app.get('/api/learning/teacher/form-drafts/review-queue',(_req,res)=>res.json({ok:true,drafts:[]}));
 app.get('/api/learning/teacher/journey-plan',(_req,res)=>res.json({ok:true,plan:{classId:'2139',totalSessions:3,highestKnownSession:2,revision:1,testSessionNumbers:[2],testSources:[],sessionDates:[]}}));
 app.get('/api/learning/teacher/dashboard',async(_req,res)=>{const notes=await currentNotes();res.json({ok:true,dashboard:{assignmentId:assignment,classId:'2139',className:'IC2139',sessionNumber:2,title:'Buổi thử',status:'published',publicToken:assignment,journeyCommentsEnabled:true,students:roster.map(s=>({...s,sessionComment:notes.get(s.studentRef)||null})),definition:{blocks:[]},blockReleases:[],classInsights:[]}});});
 app.get('/api/learning/teacher/live-drafts',async(_req,res)=>{const notes=await currentNotes();res.json({ok:true,live:{assignmentId:assignment,generatedAt:new Date().toISOString(),students:roster.map(s=>({...s,sessionComment:notes.get(s.studentRef)||null}))}});});
 app.get('/api/learning/teacher/assignments/:id/question-analytics',(_req,res)=>res.json({ok:true,analytics:{assignmentId:assignment,rosterCount:2,submittedCount:0,items:[]}}));
 app.use('/api/learning',createLearningRouter({pool,authenticate:(req,_res,next)=>{req.reviewer=reviewer;next();},journeyCommentsEnabled:true,progressLinkKeys:{v1:Buffer.alloc(32,17).toString('base64')}}));
 app.get('/progress-log/config.js',(_req,res)=>res.type('js').send(`window.PROGRESS_LOG_CONFIG={API_BASE_URL:location.origin};`));
 app.use(express.static(pages));
 const server=await new Promise(done=>{const listener=app.listen(0,'127.0.0.1',()=>done(listener));});
 const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({channel:'chrome',headless:true});
 const errors=[];let loseResponse=false;
 const output=process.env.JOURNEY_TEST_OUTPUT||resolve(pages,'output/playwright');await mkdir(output,{recursive:true});
 try{
  const context=await browser.newContext({viewport:{width:1234,height:900}});
  await context.route('https://accounts.google.com/**',route=>route.fulfill({contentType:'text/javascript',body:''}));
  await context.route('**/api/learning/teacher/session-comments',async route=>{if(loseResponse){loseResponse=false;await route.fetch();return route.abort('connectionfailed');}return route.continue();});
  const teacher=await context.newPage();teacher.setDefaultTimeout(10000);teacher.on('pageerror',e=>errors.push(e.message));
  await teacher.goto(origin+'/progress-log/teacher.html');await teacher.locator('#studentList .student-row').first().waitFor();
  const row=teacher.locator('#studentList .student-row').first();
  assert.equal(await row.getByRole('button',{name:'Xem bài nộp',exact:true}).count(),0);
  const styles=await row.locator('.student-actions button').evaluateAll(es=>es.filter(e=>!e.hidden).map(e=>{const s=getComputedStyle(e);return [s.fontWeight,s.backgroundColor,s.borderColor,e.getBoundingClientRect().height];}));
  assert.deepEqual(styles[0],styles[1]);
  await row.click({position:{x:8,y:8}});await teacher.locator('#journeyDetailDialog').waitFor({state:'visible'});
  const input=teacher.locator('#journeyDetailDialog textarea').last();await input.fill('Bản đang gõ giữ lại.');
  await teacher.mouse.click(2,2);await teacher.locator('#journeyDetailDialog').waitFor({state:'hidden'});
  await row.focus();await teacher.keyboard.press('Enter');await input.waitFor();assert.equal(await input.inputValue(),'Bản đang gõ giữ lại.');
  await teacher.keyboard.press('Escape');await row.getByRole('button',{name:'Thêm nhận xét',exact:true}).click();await input.waitFor();
  const note='Em đọc tốt hơn.\n<script>window.hacked=true</script>';await input.fill(note);loseResponse=true;
  const save=teacher.getByRole('button',{name:'Lưu và hiển thị với học viên'});await save.click();await teacher.locator('.session-comment-editor .notice').filter({hasText:/Failed to fetch|fetch/i}).waitFor();
  await save.click();await teacher.locator('.session-comment-editor .notice').filter({hasText:'Đã lưu'}).waitFor();
  assert.equal((await pool.query('SELECT count(*)::int AS n FROM learning.student_session_comment_revision')).rows[0].n,1);
  await teacher.keyboard.press('Escape');assert.equal(await row.locator('.session-comment p').textContent(),note);
  await teacher.screenshot({path:resolve(output,'journey-teacher-comment.png'),fullPage:true});
  const popupPromise=context.waitForEvent('page');await row.getByRole('button',{name:'Hành trình riêng ↗'}).click();const student=await popupPromise;
  student.setDefaultTimeout(10000);student.on('pageerror',e=>errors.push(e.message));await student.locator('.latest-session-comment').waitFor();
  const originalURL=student.url();assert.match(originalURL,/#access=/);assert.equal(await student.evaluate(()=>window.hacked),undefined);
  await student.reload();await student.locator('.latest-session-comment').waitFor();assert.equal(student.url(),originalURL);
  await student.locator('#timelineToggle').click();await student.getByLabel('Lọc buổi học theo nhận xét').selectOption('comments');assert.equal(await student.locator('#sessionList > :visible').count(),1);
  await student.screenshot({path:resolve(output,'journey-student-comment.png'),fullPage:true});
  await student.locator('#sessionList [data-session-number="2"]').click();await student.locator('#journeyDetailDialog .session-comment').waitFor();assert.match(await student.locator('#journeyDetailDialog').innerText(),/Em đọc tốt hơn/);
  await student.keyboard.press('Escape');
  await row.getByRole('button',{name:'Nhận xét',exact:true}).click();await input.waitFor();await input.fill('Bản cũ đang sửa');
  const response=await fetch(origin+'/api/learning/teacher/session-comments',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({classId:'2139',studentRef:ref,sessionNumber:2,noteText:'Giáo viên khác đã cập nhật',expectedRevision:1,operationId:crypto.randomUUID()})});assert.equal(response.status,200);
  await save.click();await teacher.getByRole('button',{name:'Tải nhận xét hiện hành, giữ bản đang gõ'}).waitFor();assert.equal(await input.inputValue(),'Bản cũ đang sửa');
  await teacher.getByRole('button',{name:'Tải nhận xét hiện hành, giữ bản đang gõ'}).click();await teacher.locator('.session-comment-editor .notice').filter({hasText:'Đã đọc bản hiện hành'}).waitFor();
  await save.click();await teacher.locator('.session-comment-editor .notice').filter({hasText:'Đã lưu'}).waitFor();
  teacher.once('dialog',dialog=>dialog.accept());await teacher.getByRole('button',{name:'Ẩn nhận xét',exact:true}).click();await teacher.locator('.session-comment-editor .notice').filter({hasText:'Đã ẩn'}).waitFor();
  await student.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await student.locator('.latest-session-comment').waitFor({state:'hidden'});assert.equal(await student.locator('[data-session-comment]').count(),0);
  await teacher.getByRole('button',{name:'Quản lý link Hành trình riêng'}).click();await teacher.locator('.journey-link-dialog p').filter({hasText:'Link không hết hạn'}).waitFor();
  const accessId=(await pool.query("SELECT id FROM learning.student_progress_access WHERE student_ref=$1 AND status='active'",[ref])).rows[0].id;
  const replaced=await fetch(origin+'/api/learning/teacher/student-progress-links/rotate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({classId:'2139',studentRef:ref,expectedAccessId:accessId,operationId:crypto.randomUUID()})});const replacement=await replaced.json();assert.equal(replaced.status,200);
  teacher.once('dialog',dialog=>dialog.accept());await teacher.locator('.journey-link-dialog').getByRole('button',{name:'Thay link',exact:true}).click();
  await teacher.locator('.journey-link-dialog p').filter({hasText:'Bấm Thử lại để đọc trạng thái hiện hành'}).waitFor();
  await teacher.locator('.journey-link-dialog').getByRole('button',{name:'Thử lại',exact:true}).click();
  await teacher.waitForFunction(token=>document.querySelector('.journey-link-dialog input').value.includes(token),replacement.link.accessToken);
  assert.equal((await pool.query('SELECT count(*)::int AS n FROM learning.student_progress_access')).rows[0].n,2);
  await teacher.keyboard.press('Escape');
  await teacher.keyboard.press('Escape');await teacher.getByRole('button',{name:'Hành trình lớp',exact:true}).click();await teacher.locator('.comment-disclosure').first().waitFor();
  assert.equal(await teacher.locator('.comment-disclosure[open]').count(),0);
  assert.equal(await teacher.locator('.comment-disclosure > summary').first().evaluate(e=>getComputedStyle(e,'::after').color),'rgb(219, 62, 75)');
  await teacher.locator('.comment-disclosure > summary').first().click({position:{x:8,y:8}});assert.equal(await teacher.locator('.comment-disclosure[open]').count(),1);
  for(const width of [390,768,1440]){await teacher.setViewportSize({width,height:900});await student.setViewportSize({width,height:900});
    assert.ok(await teacher.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await student.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await teacher.screenshot({path:resolve(output,'journey-teacher-'+width+'.png'),fullPage:true});await student.screenshot({path:resolve(output,'journey-student-'+width+'.png'),fullPage:true});}
  const counts=await pool.query(`SELECT (SELECT count(*) FROM learning.attempt)::int AS attempts,(SELECT count(*) FROM learning.submission)::int AS submissions,(SELECT count(*) FROM learning.attendance_event)::int AS events,(SELECT count(*) FROM learning.outbox_job)::int AS jobs`);
  assert.deepEqual(counts.rows[0],{attempts:0,submissions:0,events:0,jobs:0});assert.deepEqual(errors,[]);
 }finally{await browser.close();server.closeAllConnections();await new Promise(done=>server.close(done));await database.close();}
});
